sudo: false
install: true

addons:
  sonarcloud:
    organization: "paru"
    token:
      secure: "o0j9ZikVd4QyKaei6dXRj8LAhDV1k1NJPXAOyyRgPK8TbRrjUnsXjwA/JT94MFeaqJ+sMIj9s50OYqMRuUGiVfOIklogCNq687S5UFZRiq2j9CUzdaK5Vw59QZAggHutd2Hrzz/lTr7O/AIZV0Lbu9sHBotNgisetYqPVETW/WDR6hZsfUXuHQhTc/sLrcYD6QTpyqvM1xeUs/ddPLuTRW2YsE2WwkiJkQ9fEHGEyditann6EmuhUX2ly80o7LO+iQeoWNoE7AbCIpW58QjEVE3jqqPr76ubOIXudEbN3SnGb3bbs5hoJ8ccp8TXwcEM1CB/6Q5WpsZlTv3cLAY+5WExs3gYHBgyom/oWoaxaUNrxKgZLGH4bCq+8jvSqWCBTZ1oPDaxJ2ePIGPAtUFsXL8NQZDpcuFj73J8ISHZ9Ant8NjIyCveCyaJkVlphUYQQgP8Rde2Y+jlK9q3Ls8jBnxgQkeJU0Gfw2YQsfkl7JTwnmamNJz1qSHYrINLjglN4MgZMVfLi79BOONBXuXjSh2ZU4mRU2Fcfg34KDfkqD1Y24voKJ0x0h8CtliE/BiTN5ApKrUv2A60jIq9xN6f4VVyTKHoxL8x0rc7T9OoYyGqfLMdj47dOYOWnyPLqfBEwHmGxtwRsMn+xBC0GgFHLNQgEloEdIvEXD3h9kIrujY="

script:
  - mvn clean verify sonar:sonar -Pcoverage 
