language: java

dist: trusty

addons:
  sonarcloud:
    organization: "Akshay C A"
    token:
      secure: ${SONAR_TOKEN}
      

script:
    - mvn clean verify sonar:sonar -Pcoverage -Dsonar.projectKey=workspace_bdd

